-- SQL seed for credentials table (generated from CSV)
-- Usage: Run in Supabase SQL editor or psql

INSERT INTO credentials (service_tags, industry_tags, title, is_active, sort_order) VALUES
('{Feasibility Study,"Business Strategy"}', '{Industrial}', 'Pre-feasibility study and business strategy for Gold Bar manufacturing business', true, 0),
('{Business Valuation}', '{Infrastructure}', 'Business valuation for a leading Ports Development Company', true, 0),
('{Business Valuation}', '{Infrastructure}', 'Business valuation for an Infrastructure and Marine Contracting Company', true, 0),
('{Turnaround Advisory}', '{Infrastructure}', 'Business diagnostics and strategic advisory for a Marine Contracting Company', true, 0),
('{Restructuring,"Business Strategy"}', '{Infrastructure}', 'Strategy consulting service for restructuring of a Marine Contracting Company', true, 0),
('{Feasibility Study}', '{Industrial}', 'Feasibility study for a Hot Dip Galvanizing plant with a capacity of 50,000 TPA', true, 0),
('{Feasibility Study,"Business Strategy"}', '{Healthcare,Real Estate}', 'Feasibility study and strategy for a Speciality Clinic & Rehabilitation Center', true, 0),
('{Feasibility Study,"Business Strategy"}', '{Healthcare,Real Estate,Entertainment}', 'Feasibility study and business strategy for a Niche Market Care Center', true, 0),
('{Business Valuation}', '{Consumer,Technology}', 'Business valuation for a Consumer Electronics business', true, 0),
('{Investor Documents,Transaction Advisory}', '{Consumer,Technology}', 'Investor documents for a Consumer Electronics business to raise Growth Capital', true, 0),
('{Turnaround Advisory}', '{Consumer,Industrial}', 'Turnaround advisory for a Cosmetics Manufacturing business', true, 0),
('{Business Valuation}', '{Consumer,Industrial}', 'Business valuation for a Cosmetics Manufacturing business', true, 0),
('{Investor Documents,Transaction Advisory}', '{Consumer,Industrial}', 'Transaction advisory for a Consumer Products business to raise growth capital', true, 0),
('{Transaction Advisory,"Business Strategy"}', '{Education,Technology}', 'Strategic and transaction advisory for an Ed-Tech business to raise growth capital', true, 0),
('{Commercial Due Diligence}', '{Industrial}', 'Commercial due diligence on Hot Dip Galvanizing industry for an EMEA country', true, 0),
('{Growth Strategy}', '{Logistics}', 'Growth strategy for Logistics business in Transportation, Supply Chain and Storage sectors', true, 0),
('{Transaction Advisory,Investor Documents}', '{Logistics}', 'Transaction advisory for a business operating in Logistics Industry to raise growth capital', true, 0),
('{Pro Bono}', '{Logistics}', 'Strategic review of Business Plan for an e-commerce startup focused on niche B2C market', true, 0),
('{Portfolio Valuation}', '{Technology}', 'Portfolio valuation mandate to value a VC fund and its portfolio investments', true, 0),
('{Business Valuation}', '{Technology}', 'Business valuation of 18 investments for a Venture Builder and Investor', true, 0),
('{Value Creation,"Business Strategy"}', '{Technology}', 'Value creation strategy on 9 portfolio companies of a Private Capital investor', true, 0),
('{Transaction Advisory,Commercial Due Diligence,Financial Due Diligence,Business Valuation}', '{Technology}', 'Investor due diligence, business valuation, and deal advisory on 4 deals for a PE & VC fund', true, 0),
('{Restructuring,"Business Strategy"}', '{Infrastructure}', 'Preparation of FRP based on multiple scenarios for a Corporation with assets valued +$6 Bn', true, 0),
('{Business Valuation,Transaction Advisory,Investor Documents}', '{Technology}', 'Sell side M&A advisory for a Software Consultancy and Implementation company', true, 0),
('{Feasibility Study}', '{Healthcare}', 'Feasibility study for a Tertiary Care Diagnostics and Treatment Center with 6 phases', true, 0),
('{Transaction Advisory,Investor Documents}', '{Healthcare}', 'Transaction advisory for an Oncology Center with multiple greenfield and brownfield clinics', true, 0),
('{Feasibility Study}', '{Industrial,Energy}', 'Feasibility Study for an LSAW Pipe Manufacturing greenfield project', true, 0),
('{Commercial Due Diligence,Financial Due Diligence,Business Valuation}', '{Technology}', 'Comprehensive investor due diligence for a Fully Integrated Payment Solutions company', true, 0),
('{Commercial Due Diligence,Financial Due Diligence,Business Valuation}', '{Technology}', 'Comprehensive investor due diligence for a Rent Now Pay Later company', true, 0),
('{Commercial Due Diligence,Financial Due Diligence,Business Valuation}', '{Technology}', 'Comprehensive investor due diligence  for a Revenue Based Financing business', true, 0),
('{Commercial Due Diligence,Financial Due Diligence,Business Valuation}', '{Technology}', 'Comprehensive investor due diligence for FIDO Powered Payment Solutions company', true, 0),
('{Feasibility Study}', '{Industrial,Energy}', 'Feasibility study for Electric Vehicle Chargers Manufacturing business', true, 0),
('{Commercial Due Diligence}', '{Industrial}', 'Commercial due diligence on Water Filters Manufacturing business', true, 0),
('{Business Valuation,Portfolio Valuation}', '{Technology}', 'Business valuation of an e-commerce business focusing on Auctions & Sealed Envelopes', true, 0),
('{Business Valuation,Portfolio Valuation}', '{Technology}', 'Business valuation of an e-commerce logistics company for Cosmetics Products', true, 0),
('{Business Valuation,Portfolio Valuation}', '{Technology}', 'Business valuation of an e-commerce logistics company for Food and Beverages SMEs', true, 0),
('{Business Valuation,Portfolio Valuation}', '{Technology}', 'Business valuation of an e-commerce business specializing in Luxury Personal Shopping', true, 0),
('{Business Valuation,Portfolio Valuation}', '{Technology}', 'Business valuation of an e-commerce business selling Thobe and Abayas', true, 0),
('{Business Valuation,Portfolio Valuation}', '{Technology}', 'Business valuation of an e-commerce Supply Chain Solutions Company selling Spare Parts', true, 0),
('{Business Valuation,Portfolio Valuation}', '{Technology}', 'Business valuation of an e-commerce Supply Chain company offering Fresh Produce', true, 0),
('{Business Valuation,Portfolio Valuation}', '{Technology}', 'Business valuation of an e-commerce Marketplace for Luxury Fashion Products', true, 0),
('{Feasibility Study}', '{Industrial}', 'Feasibility study for Manufacturing of Food Packaging Materials from PET and PP', true, 0),
('{Feasibility Study}', '{Industrial}', 'Feasibility study for Expansion of Manufacturing of Food Packaging Materials', true, 0),
('{Feasibility Study}', '{Industrial,Energy}', 'Feasibility study for Fabrication and Galvanization of Steel Towers, and Solar Beams, Torque Tubes & Fasteners', true, 0),
('{Feasibility Study}', '{Healthcare}', 'Feasibility study for a Cancer Treatment Center with the Latest Technology', true, 0),
('{Feasibility Study}', '{Healthcare}', 'Feasibility study for a Healthcare Equipment Regulatory Audit business', true, 0),
('{Business Valuation}', '{Healthcare}', 'Business valuation for a Pharmaceuticals and Healthcare Equipment Trading business', true, 0),
('{Business Valuation}', '{Healthcare}', 'Business valuation for a Surgical Equipment Trading business', true, 0),
('{Feasibility Study}', '{Technology}', 'Feasibility study for a Home-based Spa Services business', true, 0),
('{Business Valuation}', '{Healthcare}', 'Business valuation for a Pharmaceutical Products Trading and Distribution business', true, 0),
('{Transaction Advisory}', '{Healthcare}', 'Sell side M&A advisory for a Pharmaceutical Products Trading and Distribution business', true, 0),
('{Business Strategy,Business Valuation and Investor Documents}', '{Technology}', 'Business plan, business valuation and investor documents for an AI business', true, 0),
('{Feasibility Study}', '{Real Estate}', 'HBU study for a Mixed Use Development with Residential and Retail components', true, 0),
('{Business Strategy,Business Valuation and Investor Documents}', '{Technology}', 'Business plan, business valuation and investor documents for a B2B marketplace', true, 0),
('{Feasibility Study}', '{Food & Agriculture}', 'Feasibility study for a Large Scale Fully Integrated Poultry project', true, 0),
('{Business Valuation,Strategic Options Analysis}', '{Energy}', 'Business valuation and Strategic Options Analysis for an Oil Well Drilling Contracting Company', true, 0),
('{Business Valuation}', '{Healthcare}', 'Business valuation for a Cosmetic Clinic as a business unit of a hospital', true, 0),
('{Feasibility Study}', '{Industrial}', 'Feasibility study for a Ductile Iron Pipe Manufacturing greenfield project', true, 0),
('{Feasibility Study}', '{Industrial}', 'Feasibility study for a large scale Pipe Manufacturing project with multiple types of Pipes', true, 0),
('{Feasibility Study}', '{Industrial,Energy,Food & Agriculture,Infrastructure}', 'Pre-feasibility study for a Chemical Manufacturing Plant with applications in Mining, Water Treatment and Agricultural sectors', true, 0),
('{Feasibility Study}', '{Industrial,Energy}', 'Pre-feasibility study for a Chemical Manufacturing Plant with applications in Mining sector', true, 0),
('{Feasibility Study}', '{Industrial,Healthcare}', 'Feasibility study for a Healthcare Products Manufacturing business with applications in Oncology and Critical Care', true, 0),
('{Transaction Support,Business Valuation}', '{Technology}', 'Financial modeling and analysis for a Crypto Business operating in Two Countries (Europe and GCC)', true, 0); 