'use client'

import { useState, useEffect } from 'react';
import { Insight } from '@/lib/types/cms';
import TipTapEditor from './TipTapEditor';
import ImageUpload from './ImageUpload';
import { useRouter } from 'next/navigation';

interface InsightFormProps {
  insight?: Insight | null;
  onClose: () => void;
  onSuccess: () => void;
}

export default function InsightForm({ insight, onClose, onSuccess }: InsightFormProps) {
  const [formData, setFormData] = useState({
    title: '',
    excerpt: '',
    content: '',
    image_url: '',
    author: '',
    co_author: '',
    published_date: '',
    is_published: false,
    meta_description: '',
    tags: [] as string[],
  });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [newTag, setNewTag] = useState('');
  const [seo, setSeo] = useState({
    title: '',
    description: '',
    keywords: '',
    canonical_url: '',
    og_title: '',
    og_description: '',
    og_image: '',
    twitter_title: '',
    twitter_description: '',
    twitter_image: '',
  });
  const [showSeo, setShowSeo] = useState(false);
  const router = useRouter();

  // Predefined tags
  const predefinedTags = [
    'Corporate Finance', 'Investment Consulting&A', 'Strategy Consulting', 'Turnaround and Restructuring'
  ];

  useEffect(() => {
    if (insight) {
      setFormData({
        title: insight.title || '',
        excerpt: insight.excerpt || '',
        content: insight.content || '',
        image_url: insight.image_url || '',
        author: insight.author || '',
        co_author: insight.co_author || '',
        published_date: insight.published_date || '',
        is_published: insight.is_published ?? false,
        meta_description: insight.meta_description || '',
        tags: insight.tags || [],
      });
      setSeo({
        title: insight.seo?.title || '',
        description: insight.seo?.description || '',
        keywords: insight.seo?.keywords || '',
        canonical_url: insight.seo?.canonical_url || '',
        og_title: insight.seo?.og_title || '',
        og_description: insight.seo?.og_description || '',
        og_image: insight.seo?.og_image || '',
        twitter_title: insight.seo?.twitter_title || '',
        twitter_description: insight.seo?.twitter_description || '',
        twitter_image: insight.seo?.twitter_image || '',
      });
    }
  }, [insight]);

  // Autogenerate SEO defaults (WordPress-style)
  const autoSeo = {
    title: seo.title || formData.title,
    description: seo.description || formData.excerpt || (formData.content ? formData.content.replace(/<[^>]+>/g, '').slice(0, 160) : ''),
    keywords: seo.keywords || (formData.tags ? formData.tags.join(', ') : ''),
    canonical_url: seo.canonical_url || '', // You may want to generate the public URL here
    og_title: seo.og_title || seo.title || formData.title,
    og_description: seo.og_description || seo.description || formData.excerpt,
    og_image: seo.og_image || formData.image_url,
    twitter_title: seo.twitter_title || seo.title || formData.title,
    twitter_description: seo.twitter_description || seo.description || formData.excerpt,
    twitter_image: seo.twitter_image || formData.image_url,
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);
    setError(null);

    // Merge admin-entered values with autogenerated defaults
    const finalSeo = {
      title: seo.title || autoSeo.title || '',
      description: seo.description || autoSeo.description || '',
      keywords: seo.keywords || autoSeo.keywords || '',
      canonical_url: seo.canonical_url || autoSeo.canonical_url || '',
      og_title: seo.og_title || autoSeo.og_title || '',
      og_description: seo.og_description || autoSeo.og_description || '',
      og_image: seo.og_image || autoSeo.og_image || '',
      twitter_title: seo.twitter_title || autoSeo.twitter_title || '',
      twitter_description: seo.twitter_description || autoSeo.twitter_description || '',
      twitter_image: seo.twitter_image || autoSeo.twitter_image || '',
    };

    try {
      const url = insight ? `/api/insights?id=${insight.id}` : '/api/insights';
      const method = insight ? 'PUT' : 'POST';
      const body = insight
        ? { ...formData, seo: finalSeo }
        : { ...formData, seo: finalSeo };

      console.log('Submitting insight:', { method, url, body, insightId: insight?.id });

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(body),
      });

      console.log('Response status:', response.status);
      const responseData = await response.json();
      console.log('Response data:', responseData);

      if (!response.ok) {
        throw new Error(responseData.error || 'Failed to save insight');
      }

      // Clear cache to ensure fresh data
      try {
        await fetch('/api/cache/clear', { method: 'POST' });
      } catch (cacheError) {
        console.warn('Failed to clear cache:', cacheError);
      }

      // In the handleSubmit, after a successful response and cache clear, call onSuccess() if provided
      if (onSuccess) onSuccess();
    } catch (error) {
      console.error('Error submitting insight:', error);
      setError(error instanceof Error ? error.message : 'An error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  const handleAddTag = () => {
    if (newTag.trim() && !formData.tags.includes(newTag.trim())) {
      setFormData(prev => ({
        ...prev,
        tags: [...prev.tags, newTag.trim()]
      }));
      setNewTag('');
    }
  };

  const handleRemoveTag = (tagToRemove: string) => {
    setFormData(prev => ({
      ...prev,
      tags: prev.tags.filter(tag => tag !== tagToRemove)
    }));
  };

  const handlePredefinedTagToggle = (tag: string) => {
    if (formData.tags.includes(tag)) {
      handleRemoveTag(tag);
    } else {
      setFormData(prev => ({
        ...prev,
        tags: [...prev.tags, tag]
      }));
    }
  };

  return (
    <div className="bg-white p-10">

      <form onSubmit={handleSubmit} className="space-y-8">
        
        {/* Feature Image */}
        <div className='grid grid-cols-1 md:grid-cols-2 gap-8'>
          <div>
              <ImageUpload
                onUploadComplete={(url) => setFormData(prev => ({ ...prev, image_url: url }))}
                onError={(error) => {
                  console.error('Image upload error:', error);
                  alert(`Upload failed: ${error}`);
                }}
                currentImage={formData.image_url}
                placeholder="Upload feature image for this insight"
                maxSize={5}
                className=""
                label="Feature Image"
              />
            </div>
            <div className='flex flex-col gap-8'>
              {/* Title */}
              <div>
                <label htmlFor="title" className="block text-sm font-medium text-gray-700">
                  Title *
                </label>
                <input
                  type="text"
                  id="title"
                  required
                  value={formData.title}
                  onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
                  className="mt-1 block w-full   border-b border-dark/5 focus:ring-dark focus:border-dark sm:text-sm"
                  placeholder="Enter insight title"
                />
              </div>

              {/* Excerpt */}
              <div>
                <label htmlFor="excerpt" className="block text-sm font-medium text-gray-700">
                  Excerpt *
                </label>
                <textarea
                  id="excerpt"
                  required
                  rows={3}
                  value={formData.excerpt}
                  onChange={(e) => setFormData(prev => ({ ...prev, excerpt: e.target.value }))}
                  className="mt-1 block w-full   border-b border-dark/5 focus:ring-dark focus:border-dark sm:text-sm"
                  placeholder="Enter a brief excerpt"
                />
              </div>

              
            {/* Author */}
            <div>
              <label htmlFor="author" className="block text-sm font-medium text-gray-700">
                Author *
              </label>
              <input
                type="text"
                id="author"
                required
                value={formData.author}
                onChange={(e) => setFormData(prev => ({ ...prev, author: e.target.value }))}
                className="mt-1 block w-full   border-b border-dark/5 focus:ring-dark focus:border-dark sm:text-sm"
                placeholder="Enter author name"
              />
            </div>

            {/* Co-Author */}
            <div>
              <label htmlFor="co_author" className="block text-sm font-medium text-gray-700">
                Co-Author
              </label>
              <input
                type="text"
                id="co_author"
                value={formData.co_author}
                onChange={(e) => setFormData(prev => ({ ...prev, co_author: e.target.value }))}
                className="mt-1 block w-full   border-b border-dark/5 focus:ring-dark focus:border-dark sm:text-sm"
                placeholder="Enter co-author name (optional)"
              />
            </div>
            </div>
        </div>

        {/* Content and Preview side by side */}
        <div>
          <label htmlFor="content" className="block text-sm font-medium text-gray-700 mb-2">
            Content
          </label>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div>
              <TipTapEditor
                value={formData.content}
                onChange={(value: string) => setFormData(prev => ({ ...prev, content: value }))}
                placeholder="Enter the full content with rich formatting..."
                className="mt-1"
              />
            </div>
            <div>
              <div 
                className="p-3 border border-gray-200 bg-gray-50 min-h-[120px] prose prose-sm"
                dangerouslySetInnerHTML={{ __html: formData.content }}
              />
            </div>
          </div>
        </div>


            {/* Published Date */}
            <div>
              <label htmlFor="published_date" className="block text-sm font-medium text-gray-700">
                Published Date
              </label>
              <input
                type="date"
                id="published_date"
                value={formData.published_date}
                onChange={(e) => setFormData(prev => ({ ...prev, published_date: e.target.value }))}
                className="mt-1 block w-full   border-b border-dark/5 focus:ring-dark focus:border-dark sm:text-sm"
              />
            </div>

            {/* Meta Description */}
            {/* <div>
              <label htmlFor="meta_description" className="block text-sm font-medium text-gray-700">
                Meta Description
              </label>
              <textarea
                id="meta_description"
                rows={2}
                value={formData.meta_description}
                onChange={(e) => setFormData(prev => ({ ...prev, meta_description: e.target.value }))}
                className="mt-1 block w-full   border-b border-dark/5 focus:ring-dark focus:border-dark sm:text-sm"
                placeholder="SEO meta description"
              />
            </div> */}

            {/* Tags */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Tags
              </label>
              
              {/* Predefined Tags */}
              <div className="mb-4">
                <p className="text-sm text-gray-600 mb-2">Predefined tags:</p>
                <div className="flex flex-wrap gap-2">
                  {predefinedTags.map((tag) => (
                    <button
                      key={tag}
                      type="button"
                      onClick={() => handlePredefinedTagToggle(tag)}
                      className={`px-3 py-1 text-xs  ${
                        formData.tags.includes(tag)
                          ? 'bg-dark text-white'
                          : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                      }`}
                    >
                      {tag}
                    </button>
                  ))}
                </div>
              </div>

              {/* Custom Tags */}
              <div className="flex gap-2 mb-2">
                <input
                  type="text"
                  value={newTag}
                  onChange={(e) => setNewTag(e.target.value)}
                  onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), handleAddTag())}
                  className="flex-1   border-b border-dark/5 focus:ring-dark focus:border-dark sm:text-sm"
                  placeholder="Add custom tag"
                />
                <button
                  type="button"
                  onClick={handleAddTag}
                  className="px-3 py-2 bg-gray-600 text-white  hover:bg-gray-700"
                >
                  Add
                </button>
              </div>

              {/* Selected Tags */}
              {formData.tags.length > 0 && (
                <div className="flex flex-wrap gap-2">
                  {formData.tags.map((tag, index) => (
                    <span
                      key={index}
                      className="inline-flex items-center px-2.5 py-0.5  text-xs font-medium bg-purple-100 text-purple-800"
                    >
                      {tag}
                      <button
                        type="button"
                        onClick={() => handleRemoveTag(tag)}
                        className="ml-1 text-purple-600 hover:text-purple-800"
                      >
                        ×
                      </button>
                    </span>
                  ))}
                </div>
              )}
            </div>

            {/* Published Status */}
            <div>
              <label className="flex items-center">
                <input
                  type="checkbox"
                  checked={formData.is_published}
                  onChange={(e) => setFormData(prev => ({ ...prev, is_published: e.target.checked }))}
                  className="rounded  text-dark focus:ring-dark"
                />
                <span className="ml-2 text-sm text-gray-700">Published</span>
              </label>
            </div>

            {error && (
              <div className=" bg-red-50 p-4">
                <div className="flex">
                  <div className="ml-3">
                    <h3 className="text-sm font-medium text-red-800">
                      {error}
                    </h3>
                  </div>
                </div>
              </div>
            )}

        <div>
          <button
            type="button"
            className="text-blue-600 underline mb-2"
            onClick={() => setShowSeo((v) => !v)}
          >
            {showSeo ? 'Hide SEO Settings' : 'Show SEO Settings'}
          </button>
          {showSeo && (
            <div className="space-y-4 border p-4 rounded bg-gray-50">
              <div>
                <label className="block font-medium mb-1">SEO Title</label>
                <input
                  type="text"
                  value={seo.title || autoSeo.title || ''}
                  onChange={e => setSeo(prev => ({ ...prev, title: e.target.value }))}
                  className="w-full border p-2 rounded"
                />
              </div>
              <div>
                <label className="block font-medium mb-1">SEO Description</label>
                <textarea
                  value={seo.description || autoSeo.description || ''}
                  onChange={e => setSeo(prev => ({ ...prev, description: e.target.value }))}
                  className="w-full border p-2 rounded"
                />
              </div>
              <div>
                <label className="block font-medium mb-1">SEO Keywords</label>
                <input
                  type="text"
                  value={seo.keywords || autoSeo.keywords || ''}
                  onChange={e => setSeo(prev => ({ ...prev, keywords: e.target.value }))}
                  className="w-full border p-2 rounded"
                />
              </div>
              <div>
                <label className="block font-medium mb-1">Canonical URL</label>
                <input
                  type="text"
                  value={seo.canonical_url || autoSeo.canonical_url || ''}
                  onChange={e => setSeo(prev => ({ ...prev, canonical_url: e.target.value }))}
                  className="w-full border p-2 rounded"
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block font-medium mb-1">OG Title</label>
                  <input
                    type="text"
                    value={seo.og_title || autoSeo.og_title || ''}
                    onChange={e => setSeo(prev => ({ ...prev, og_title: e.target.value }))}
                    className="w-full border p-2 rounded"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">OG Description</label>
                  <input
                    type="text"
                    value={seo.og_description || autoSeo.og_description || ''}
                    onChange={e => setSeo(prev => ({ ...prev, og_description: e.target.value }))}
                    className="w-full border p-2 rounded"
                  />
                </div>
                <div>
                  <ImageUpload
                    label="OG Image"
                    currentImage={seo.og_image || ''}
                    onUploadComplete={url => setSeo(prev => ({ ...prev, og_image: url }))}
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">Twitter Title</label>
                  <input
                    type="text"
                    value={seo.twitter_title || autoSeo.twitter_title || ''}
                    onChange={e => setSeo(prev => ({ ...prev, twitter_title: e.target.value }))}
                    className="w-full border p-2 rounded"
                  />
                </div>
                <div>
                  <label className="block font-medium mb-1">Twitter Description</label>
                  <input
                    type="text"
                    value={seo.twitter_description || autoSeo.twitter_description || ''}
                    onChange={e => setSeo(prev => ({ ...prev, twitter_description: e.target.value }))}
                    className="w-full border p-2 rounded"
                  />
                </div>
                <div>
                  <ImageUpload
                    label="Twitter Image"
                    currentImage={seo.twitter_image || ''}
                    onUploadComplete={url => setSeo(prev => ({ ...prev, twitter_image: url }))}
                  />
                </div>
              </div>
            </div>
          )}
        </div>

        <div className="flex justify-end space-x-3 pt-6">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 border border-dark/10 text-sm font-medium text-dark hover:bg-surface focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-dark"
          >
            Cancel
          </button>
          <button
            type="submit"
            disabled={isLoading || !formData.title || !formData.excerpt || !formData.author}
            className="px-4 py-2 bg-dark text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-dark disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {isLoading ? 'Saving...' : (insight ? 'Update' : 'Create')}
          </button>
        </div>
      </form>
    </div>
  );
} 